### ISSUE TITLE
Compare writable IPFS gateway with js-ipfs-fetch

### ISSUE THREAD

**Issue by RangerMauve** [AgregoreWeb/agregore-ipfs-daemon#2]
The project will use a forked version of the IPFS [gateway code](https://github.com/ipfs/go-ipfs/tree/master/core/corehttp), and have it match [js-ipfs-fetch](https://github.com/RangerMauve/js-ipfs-fetch).

Gateway behaviour is documented in the code, and there are some amateur docs from 2017 [here](https://discuss.ipfs.io/t/writeable-http-gateways/210).

## Gateway-only features
- IPNS resolution through DNS
- Browser specific features
	- [Custom filenames](https://github.com/ipfs/go-ipfs/blob/master/docs/gateway.md#filenames)
	- [Force downloads](https://github.com/ipfs/go-ipfs/blob/master/docs/gateway.md#downloads)
- Etags, so browser cache can be used
- Good mimetype detection using https://github.com/gabriel-vasile/mimetype
- Able to do direct file upload (no wrapping directory)
- Remove files from existing trees with DELETE
- Add files to existing trees with PUT

## js-ipfs-fetch features (checked off as our gateway fork adds them)
- [x] JSON directory listing c4dd90f
- [x] `X-Resolve: none` means that `index.html` isn't served 88710cd
	- [x] Switch to query string `?noResolve` 12e7d39
- [x] Upload multiple files in one request using FormData 0768d45
- [x] Update IPNS using IPFS path (POST) af4e31b
- [x] Update IPNS using data to be hashed (PUT) 5b416b3
- [x] Upload multiple files to IPNS using FormData (PUT) 5b416b3
- [x] IPNS DELETE 29d4972

**Comment by makew0rld** [comment]
Features are completed. Once an API/gateway spec is finished some code will change to conform to that spec.
